In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
#make Qtable initialize to 0
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table =np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1           # alpha
discount_rate = 0.99          # gamma  

exploration_rate =1
max_exploration_rate =1
min_exploration_rate =0.01
exploration_decay_rate =0.001

In [5]:
rewards_all_episodes =[]

#Q learning algo
for episode in range(num_episodes):            #no of episodes 
    state = env.reset()                        #resetting every env
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode):  #timesteps in same episode
        
        #exploration-exploitaion trade off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) #exploit the env
        else:
            action =env.action_space.sample()   #explore the env
            
        new_state, reward, done, info = env.step(action)#taking the action for explore or exploit
        
        #Updating Q table for new q value Q(s,a)
        q_table[state, action] = q_table[state, action]*(1-learning_rate)+ learning_rate * (reward + discount_rate  * np.max(q_table[new_state,:])) #old Q value+learned value
                                 
        state = new_state
        rewards_current_episode+= reward
        
        if done==True:
            break    
        
    #exploartion rate decay       
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)  
    
#Average rewards per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("average reward per thousand episodes")
for r in rewards_per_thousand_episodes:
    print(count, ":",str(sum(r/1000)))
    count+= 1000
    
#print updated Qtable
print("Q Table")
print(q_table)

average reward per thousand episodes
1000 : 0.035000000000000024
2000 : 0.20300000000000015
3000 : 0.4130000000000003
4000 : 0.5630000000000004
5000 : 0.6210000000000004
6000 : 0.6910000000000005
7000 : 0.6760000000000005
8000 : 0.7020000000000005
9000 : 0.6690000000000005
10000 : 0.6760000000000005
Q Table
[[0.52290172 0.49670449 0.49201881 0.49346407]
 [0.36759781 0.35088506 0.3380352  0.49375874]
 [0.425009   0.41776584 0.38062242 0.46307708]
 [0.2870017  0.32788797 0.19032834 0.4442261 ]
 [0.53454981 0.39058064 0.411208   0.40663005]
 [0.         0.         0.         0.        ]
 [0.33043902 0.16990506 0.20269446 0.13805816]
 [0.         0.         0.         0.        ]
 [0.44873435 0.38033526 0.44699696 0.56035592]
 [0.46850913 0.6049868  0.4671621  0.35144466]
 [0.54347628 0.45570837 0.37904298 0.34778377]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41715834 0.64119213 0.70237998 0.49631991]
 [0.69193784 0.82392659 0.7307533

In [7]:
for episode in range(5):
    state = env.reset()
    done = False
    print("EPISODE",episode+1,"\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()      #render the grid and the agent position
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:]) #highest q_value to take for next state
        new_state, reward, done, info =env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward==1:
                print("***Goal REACHED***")
                time.sleep(3)
            else:
                print("***u fell in the hole***")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
        
env.close()        

  (Down)
SFFF
FHFH
FFFH
HFFG
***Goal REACHED***
